executors:
    # mode and repeat are mandatory for each block
    # mode =  parallel|sequence -> execution mode
    # repeat = number of times to repeat the block
    # ha_interval = interval time between disruptions
    # sync = true|false -> enable synchronization within the block
    # node_disruption = uncomment for node level disruption , maps to logical name in disruptors.yaml
    # process_disruption = uncomment for process disruption, maps to logical name in disruptors.yaml
    # container_disruption = uncomment for container disruption, maps to logical name in disruptors.yaml
    # execute = point to the logically test name in runners.yaml
    # start = List of monitors to enable maps to logical names in monitors.yaml
    -
        # infra parameters
        mode: parallel
        repeat: 1
        sync: true
        ha_interval:  30

        # disruption scenario
        execute: [boot_test]
        start: [openstack_api, ansible]
        juju_disruption: [keystone]
