# Define your openstack VM nodes with ip and password info
control-1:
    ip: 10.30.116.198
    user: root
    password: ''
    role: controller
compute-1:
    ip: 10.30.116.199
    user : root
    password: ''
    role: compute
compute-2:
    ip: 10.30.116.200
    user: root
    password: ''
    role: compute
control-2:
    ip: 10.30.116.197
    user: root
    password: ''
    role: controller
control-3:
    ip: 10.30.116.196
    user: root
    password: ''
    role: controller
# Juju static configuration. 
# Obtain a `juju_status.yaml` file by running `juju status --format=yaml > juju_status.yaml`
juju-static:
    filename: /path/to/juju_status.yaml
    user: ubuntu
    key_filename: /path/to/ssh_key_file
    timeout: 20
